### ISSUE TITLE
Is Missouri's ID any different?

### ISSUE THREAD

**Issue by malkurwi** [c0shea/IdParser#2]
Hello there,

When I used the test IDs, all worked.
But when I use my ID (a Missouri ID), I get all null values!
Looking closer at the scanned Text (from a 2D scanner), it looks different than all other test IDs. 
I also tested a new Missouri version ID (my friend's ID), and all I got is his name!
so do you think Missouri's IDs should be handled a little different?

Thanks.

**Comment by c0shea** [comment]
It's possible that they don't conform to the AAMVA standard the way I expected or the scanner is doing something odd to the barcode. Are you able to provide a sample of the scanned text? If so, please change your personally identifiable information (e.g. name, DOB, ID Number, etc.) to sample data.

**Comment by rex644** [comment]
@
ANSI 6360300102DL00390191ZM02300053DLDAQX100097001DAALastNameTest,FirstNameTest, ,DAG123 ABC TEST ADDRESS 2ND FLDAIST LOUISDAJMODAK633011      DARF   DAS          DAT     DAU508DAW155DAYBRODBA20180204DBB20170809DBCMDBD20110630
ZMZMAST LOUIS CITYZMB112001810097ZMC          ZMD

**Comment by malkurwi** [comment]
That was a Missouri ID posted by my friend Jeff.

**Comment by rex644** [comment]
Missouri Example:
http://dor.mo.gov/pdf/newlicense.pdf

Helpful for other states:
http://dcm.uhcl.edu/caps7g8/Drivers%20License.pdf

**Comment by c0shea** [comment]
I fixed a bug in [this commit](ba7751e7ca738b33ff3ddca03b36574bdc486897) to handle licenses where M/F is used for sex instead of 0/1, which is what the standard is. I also added your Missouri example to the test project and released 3.0.2-beta, which is now available on [NuGet](https://www.nuget.org/packages/IdParser/3.0.2-beta) (updated client is also available).

That said, that doesn't explain only having the name parsed and everything else null. I'm not sure if it's GitHub removing the newlines, but can you ensure that the output from your scanner includes a carriage return followed by a line feed. Each record (DCS, DAC, DAD, etc.) should be on their own line and not all mashed together. It should look like [this](https://github.com/c0shea/IdParser/blob/master/IdParser.Test/MO%20License.txt).

**Comment by malkurwi** [comment]
I got the updated version.
I added new lines manually to the sample data that I gave you, and it worked fine.

So the problem is with my 2D barcode scanner, that is not including the NewLines.
I tried using the Scanner and PosExplorer Classes, but no luck. I don't know why I can't find any Device from the explorer.GetDevices() Method. I'm not even sure if that going to change anything!
I will probably buy a scanner that read DriverLicense properly. 

Thanks a lot for the PROJECT and for the HELP!!!

**Comment by c0shea** [comment]
If you are trying to use OPOS to communicate with your scanner, you typically need to scan a configuration barcode with the scanner, install the OPOS service objects from the vendor (e.g. Symbol), install Microsoft POS for .NET, and give the scanner a logical device name. Once you've done that, you can use [my library](https://github.com/c0shea/PointOfService) to make working with OPOS easier, or you can test it with the [IdParser.Client](https://github.com/c0shea/IdParser/releases/download/v3.0.2-beta/IdParser.Client.v3.0.2-beta.zip) app.

Otherwise, there might be some other configuration barcodes for your scanner to reset it to default settings or change the options for PDF417 barcodes. There might be something in there for the newlines not coming through.
